# Generated by Django 4.2.15 on 2024-09-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(help_text='stock id ex:00679B', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Stock name, ex 元大美債20年', max_length=20)),
                ('bid_price', models.FloatField(help_text='bid price')),
                ('price_chage_ratio', models.FloatField(help_text='price chage ratio in %')),
                ('ask_price_first', models.FloatField(help_text='ask (sell) price data 1')),
                ('ask_price_last', models.FloatField(help_text='ask (sell) price data 5')),
                ('buy_price_first', models.FloatField(help_text='buy price data 1')),
                ('buy_price_last', models.FloatField(help_text='buy price data 5')),
                ('open_price', models.FloatField(help_text='open price')),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
