# Generated by Django 4.2.15 on 2024-09-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmodel',
            name='high_price',
            field=models.FloatField(default=0.0, help_text='open price'),
        ),
        migrations.AddField(
            model_name='stockmodel',
            name='low_price',
            field=models.FloatField(default=0.0, help_text='open price'),
        ),
    ]
